### ISSUE TITLE
This extension seems to be broken

### ISSUE THREAD

**Issue by roborourke** [Chassis/memcache#21]
1. What operating system do you use?
OSX

2. What version of Vagrant are you running?
2.0.0

3. Are you using VirtualBox or VMWare and which version are you using?
Virtualbox 5.1.28

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

```yaml
php: 7.1
multisite: Yes
extensions:
  - chassis/chassis-elasticsearch
  - chassis/memcache
  - javorszky/chassis-openssl
  - chassis/cavalcade
```

5. Do you have any Chassis other extensions installed? If so, what are they?

See above.

------------

I get the following error:

```
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class memcached at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:12 on node vagrant.local
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class memcached at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:12 on node vagrant.local
```
