### ISSUE TITLE
`Memcache` not installed

### ISSUE THREAD

**Issue by banderon** [Chassis/memcache#30]
<img width="488" alt="Screen Shot 2021-05-28 at 17 40 58" src="https://user-images.githubusercontent.com/533529/120044468-ea9f8d00-bfdb-11eb-821d-46439bb4ebf1.png">

1. What operating system do you use?
> macOS 10.15.4

2. What version of Vagrant are you running?
> Vagrant 2.2.14
> Chassis 3.0.6

3. Are you using VirtualBox or VMWare and which version are you using?
> VirtualBox 6.1.18

4. Do you have a custom YAML file? If so, what does it contain?
```yaml
# Set the machine name
machine_name: tc.local

# Domain names to use for Vagrant
hosts:
  - local.techcrunch.com

# Assign a static IP addresses on the private network. /etc/hosts must be updated.
ip: 10.XX.XX.XX

# Configure SSH connection for SequelPro
ssh:
  port: 22

# Do not use multisite
multisite: No

# Extensions to install
extensions:
  - chassis/chassis_openssl
  - chassis/db_backup
  - chassis/gitignore
  - chassis/media_fallback
  - chassis/memcache
  - chassis/npm
  - chassis/phpini
  - chassis/phpmemcachedadmin
  - chassis/redirect_to_https
  - chassis/runkit7
  - chassis/sequelpro
  - chassis/tester
  - chassis/xdebug

# Configure ssl to keep the same cert/key
chassis_openssl:
  cert:
    replace: no
  key:
    replace: no

# Set the site name
site:
  name: TechCrunch (local)

# Our theme
themes:
  - techcrunch-2017

# IDE for XDebug
# (Default is PHPSTORM; update if using a different IDE)
ide: PHPSTORM

# Database configuration
# (When overriding, include all values)
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_

# Must match .circleci/config.yml and wp-tests-config.php
tester_db:
  name: circle_test
  user: testuser
  password: password

# Configure VM's MySQL server to permit importing VIP database exports.
mysql:
  mysqld:
    sql_mode:
      - 'ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE' 

# If a media file 404's within the VM, try production instead
media_fallback: 'https://techcrunch.com/wp-content'

# Manually ignore certain untracked files which may exist in the Chassis root.
gitignore:
  - '*.key' # SSL key
  - 'backups' # site DB export
  - 'chassis-backup.sql' # chassis/db_backup output

# PHP version
php: 7.4
```

5. Do you have any Chassis other extensions installed? If so, what are they?
```
  - chassis/chassis_openssl
  - chassis/db_backup
  - chassis/gitignore
  - chassis/media_fallback
  - chassis/memcache
  - chassis/npm
  - chassis/phpini
  - chassis/phpmemcachedadmin
  - chassis/redirect_to_https
  - chassis/runkit7
  - chassis/sequelpro
  - chassis/tester
  - chassis/xdebug
```
-------
While working on some code that relies on caching, I've just realized that our local caching hasn't been enabled, falling back to the built-in WP handling.

Our `object-cache.php` file is set up with:
```php
if ( ! empty( $GLOBALS['memcached_servers'] ) && class_exists( 'Memcache' ) ) {
	require_once dirname( ABSPATH ) . '/extensions/memcache/object-cache.php';
}
```
If I remove the `class_exists( 'Memcache' )` condition, I get an error that Memcache isn't installed:
<img width="736" alt="Screen Shot 2021-05-28 at 17 35 12" src="https://user-images.githubusercontent.com/533529/120044072-1e2de780-bfdb-11eb-85d9-94bfa8f93f61.png">

If I load up PHPMemcachedAdmin, I can see that there's zero activity (aside from loading PHPMemcachedAdmin itself).
![PHPMemcachedAdmin-1-3-0](https://user-images.githubusercontent.com/533529/120044290-8e3c6d80-bfdb-11eb-9d1f-c1eb5b82ede9.png)

I've reprovisioned the VM with no luck. I'd like to avoid deleting the box entirely and restarting from scratch since I don't even know whether that'd fix the issue.
